version: '3.8'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    volumes:
      - ./project:/var/www/html

  mysqldb:
    platform: linux/x86_64 # Attention : platform c'est pour les Mac M1. Commenter cette ligne pour les autres environnements.
    image: mysql:8.0
    container_name: mysql-server
    command: --authentication_policy=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # ou MYSQL_ALLOW_EMPTY_PASSWORD=true → Dans ce cas, on se connecte sans mot de passe
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${DB_PORT}:3306"

  phpmyadmin:
    image: samakunchan/phpmyadmin
    container_name: phpmyadmin-server
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${PMA_HOST}
      - UPLOAD_LIMIT='${UPLOAD_LIMIT}'
    depends_on:
      - db

volumes:
  db-data:
